<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Breeds\Commands\" />
      <Folder Include="Features\Species\Commands\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Accounts\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\..\Volunteers\KindPaws.Volunteers.Contracts\KindPaws.Volunteers.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Species.Contracts\KindPaws.Species.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Species.Domain\KindPaws.Species.Domain.csproj" />
    </ItemGroup>

</Project>
