<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DI\" />
      <Folder Include="Features\" />
      <Folder Include="Helpers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Accounts\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\KindPaws.Roles.Contracts\KindPaws.Roles.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Roles.Domain\KindPaws.Roles.Domain.csproj" />
    </ItemGroup>

</Project>
