<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\KindPaws.Users.Contracts\KindPaws.Users.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Users.Domain\KindPaws.Users.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\Models\" />
      <Folder Include="Features\Roles\Commands\" />
      <Folder Include="Features\Roles\DomainEventHandlers\" />
      <Folder Include="Features\Roles\IntegrationEventHandlers\" />
      <Folder Include="Features\Roles\Queries\" />
      <Folder Include="Features\Users\Commands\" />
      <Folder Include="Features\Users\DomainEventHandlers\" />
      <Folder Include="Features\Users\IntegrationEventHandlers\" />
      <Folder Include="Features\Users\Queries\" />
    </ItemGroup>

</Project>
