<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Accounts\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\..\Permissions\KindPaws.Permissions.Contracts\KindPaws.Permissions.Contracts.csproj" />
      <ProjectReference Include="..\..\Roles\KindPaws.Roles.Contracts\KindPaws.Roles.Contracts.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.Framework\KindPaws.Framework.csproj" />
      <ProjectReference Include="..\KindPaws.Auth.Application\KindPaws.Auth.Application.csproj" />
      <ProjectReference Include="..\KindPaws.Auth.Domain\KindPaws.Auth.Domain.csproj" />
    </ItemGroup>

</Project>
