// <auto-generated />
using System;
using System.Collections.Generic;
using KindPaws.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KindPaws.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240927213437_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Age", "KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet.Age#Age", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("DateBirth")
                                .HasColumnType("date")
                                .HasColumnName("age_date_birth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CharacteristicsDetails", "KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet.CharacteristicsDetails#PetCharacteristicsDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("Height")
                                .HasColumnType("real")
                                .HasColumnName("characteristics_details_height");

                            b1.Property<float>("Weight")
                                .HasColumnType("real")
                                .HasColumnName("characteristics_details_weight");

                            b1.ComplexProperty<Dictionary<string, object>>("Gender", "KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet.CharacteristicsDetails#PetCharacteristicsDetails.Gender#Gender", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("characteristics_details_gender_value");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.PetManagement.AggregateRoot.Pet", b =>
                {
                    b.OwnsOne("KindPaws.Domain.Managements.PetManagement.VOs.HelpDetails", "HelpDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("HelpDetails");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsOne("KindPaws.Domain.Managements.PetManagement.VOs.HelpStatus", "Status", b2 =>
                                {
                                    b2.Property<Guid>("HelpDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HelpDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_help_details_pet_id");
                                });

                            b1.OwnsMany("KindPaws.Domain.Shared.ValueObjects.Requisite", "Requisites", b2 =>
                                {
                                    b2.Property<Guid>("HelpDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HelpDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HelpDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_help_details_pet_id");
                                });

                            b1.Navigation("Requisites");

                            b1.Navigation("Status")
                                .IsRequired();
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.PetManagement.VOs.PetHealthDetails", "HealthDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("health_details_description");

                            b1.Property<bool>("IsNeutered")
                                .HasColumnType("boolean")
                                .HasColumnName("health_details_is_neutered");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("HealthDetails");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.PetManagement.VOs.Disease", "Diseases", b2 =>
                                {
                                    b2.Property<Guid>("PetHealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PetHealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetHealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_pet_health_details_pet_id");
                                });

                            b1.OwnsOne("KindPaws.Domain.Managements.PetManagement.VOs.HealthStatus", "HealthStatus", b2 =>
                                {
                                    b2.Property<Guid>("PetHealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PetHealthDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetHealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_pet_health_details_pet_id");
                                });

                            b1.OwnsMany("KindPaws.Domain.Managements.PetManagement.VOs.Vaccine", "Vaccines", b2 =>
                                {
                                    b2.Property<Guid>("PetHealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PetHealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetHealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_pet_health_details_pet_id");
                                });

                            b1.Navigation("Diseases");

                            b1.Navigation("HealthStatus")
                                .IsRequired();

                            b1.Navigation("Vaccines");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.PetManagement.VOs.PetPhotoDetails", "PhotosDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("PhotosDetails");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.PetManagement.VOs.PetPhoto", "PetPhotos", b2 =>
                                {
                                    b2.Property<Guid>("PetPhotoDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<bool>("IsMain")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("PathToStorage")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PetPhotoDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetPhotoDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_pet_photo_details_pet_id");
                                });

                            b1.Navigation("PetPhotos");
                        });

                    b.Navigation("HealthDetails")
                        .IsRequired();

                    b.Navigation("HelpDetails")
                        .IsRequired();

                    b.Navigation("PhotosDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
