// <auto-generated />
using System;
using System.Collections.Generic;
using KindPaws.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KindPaws.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241010101813_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindPaws.Domain.Managements.SpeciesManagement.AggregateRoot.Specie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "KindPaws.Domain.Managements.SpeciesManagement.AggregateRoot.Specie.Description#MediumDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "KindPaws.Domain.Managements.SpeciesManagement.AggregateRoot.Specie.Name#ShortName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpeciesManagement.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("specie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("specie_id");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "KindPaws.Domain.Managements.SpeciesManagement.Entities.Breed.Description#MediumDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "KindPaws.Domain.Managements.SpeciesManagement.Entities.Breed.Name#ShortName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_breeds");

                    b.HasIndex("specie_id")
                        .HasDatabaseName("ix_breeds_specie_id");

                    b.ToTable("breeds", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("RequisiteList")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requisites");

                    b.Property<string>("SocialNetworkList")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("social_networks");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.ComplexProperty<Dictionary<string, object>>("EmailAddress", "KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email_address");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FullName", "KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("patronymic");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_volunteers");

                    b.ToTable("volunteers", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteersManagement.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Age")
                        .HasColumnType("date")
                        .HasColumnName("age");

                    b.Property<string>("BiometricDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("biometric_details");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<bool>("_isDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("volunteer_id")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.ComplexProperty<Dictionary<string, object>>("Name", "KindPaws.Domain.Managements.VolunteersManagement.Entities.Pet.Name#ShortName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PetType", "KindPaws.Domain.Managements.VolunteersManagement.Entities.Pet.PetType#PetType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("breed_id");

                            b1.Property<Guid>("SpecieId")
                                .HasColumnType("uuid")
                                .HasColumnName("specie_id");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SupportStatus", "KindPaws.Domain.Managements.VolunteersManagement.Entities.Pet.SupportStatus#SupportStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("support_status");
                        });

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("volunteer_id")
                        .HasDatabaseName("ix_pets_volunteer_id");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpeciesManagement.Entities.Breed", b =>
                {
                    b.HasOne("KindPaws.Domain.Managements.SpeciesManagement.AggregateRoot.Specie", null)
                        .WithMany("Breeds")
                        .HasForeignKey("specie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_breeds_species_specie_id");
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer", b =>
                {
                    b.OwnsOne("KindPaws.Domain.Shared.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId")
                                .HasConstraintName("fk_volunteers_volunteers_id");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteersManagement.Entities.Pet", b =>
                {
                    b.HasOne("KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer", null)
                        .WithMany("Pets")
                        .HasForeignKey("volunteer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pets_volunteers_volunteer_id");

                    b.OwnsOne("KindPaws.Domain.Shared.ValueObjects.BaseValueObjects.MediumDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.HasKey("PetId")
                                .HasName("pk_pets");

                            b1.ToTable("pets");

                            b1.ToJson("description");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_pet_id");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.HealthDetails", "HealthDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool?>("IsNeutered")
                                .HasColumnType("boolean")
                                .HasAnnotation("Relational:JsonPropertyName", "is_neutered");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("health_details");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.Disease", "Diseases", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.HasKey("HealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.OwnsOne("KindPaws.Domain.Shared.ValueObjects.BaseValueObjects.MediumDescription", "Description", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasAnnotation("Relational:JsonPropertyName", "description");

                                    b2.HasKey("HealthDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.OwnsOne("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.HealthStatus", "HealthStatus", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasAnnotation("Relational:JsonPropertyName", "status");

                                    b2.HasKey("HealthDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.Vaccine", "Vaccines", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasAnnotation("Relational:JsonPropertyName", "name");

                                    b2.HasKey("HealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.Navigation("Description");

                            b1.Navigation("Diseases");

                            b1.Navigation("HealthStatus");

                            b1.Navigation("Vaccines");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.Lists.PetPhotoList", "PetPhotoList", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("photos_details");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.PetPhoto", "Photos", b2 =>
                                {
                                    b2.Property<Guid>("PetPhotoListPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<bool>("IsMain")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "is_main");

                                    b2.HasKey("PetPhotoListPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetPhotoListPetId")
                                        .HasConstraintName("fk_pets_pets_pet_photo_list_pet_id");

                                    b2.OwnsOne("KindPaws.Domain.Shared.ValueObjects.Photo", "Photo", b3 =>
                                        {
                                            b3.Property<Guid>("PetPhotoListPetId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("PetPhotoId")
                                                .HasColumnType("integer");

                                            b3.HasKey("PetPhotoListPetId", "PetPhotoId")
                                                .HasName("pk_pets");

                                            b3.ToTable("pets");

                                            b3.WithOwner()
                                                .HasForeignKey("PetPhotoListPetId", "PetPhotoId")
                                                .HasConstraintName("fk_pets_pets_pet_photo_list_pet_id_pet_photo_id");

                                            b3.OwnsOne("KindPaws.Domain.Shared.ValueObjects.PathToStorage", "PathToStorage", b4 =>
                                                {
                                                    b4.Property<Guid>("PhotoPetPhotoListPetId")
                                                        .HasColumnType("uuid");

                                                    b4.Property<int>("PhotoPetPhotoId")
                                                        .HasColumnType("integer");

                                                    b4.Property<string>("Value")
                                                        .IsRequired()
                                                        .HasMaxLength(2000)
                                                        .HasColumnType("character varying(2000)")
                                                        .HasAnnotation("Relational:JsonPropertyName", "path_to_storage");

                                                    b4.HasKey("PhotoPetPhotoListPetId", "PhotoPetPhotoId")
                                                        .HasName("pk_pets");

                                                    b4.ToTable("pets");

                                                    b4.WithOwner()
                                                        .HasForeignKey("PhotoPetPhotoListPetId", "PhotoPetPhotoId")
                                                        .HasConstraintName("fk_pets_pets_photo_pet_photo_list_pet_id_photo_pet_photo_id");
                                                });

                                            b3.Navigation("PathToStorage")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Photo")
                                        .IsRequired();
                                });

                            b1.Navigation("Photos");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteersManagement.ValueObjects.PetColor", "PetColor", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("color");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");
                        });

                    b.Navigation("Description");

                    b.Navigation("HealthDetails")
                        .IsRequired();

                    b.Navigation("PetColor");

                    b.Navigation("PetPhotoList")
                        .IsRequired();
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpeciesManagement.AggregateRoot.Specie", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteersManagement.AggregateRoot.Volunteer", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
