// <auto-generated />
using System;
using System.Collections.Generic;
using KindPaws.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KindPaws.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930103305_UpdateConfigurations2")]
    partial class UpdateConfigurations2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindPaws.Domain.Managements.SpecieManagement.AggregateRoot.Specie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.ToTable("species", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpecieManagement.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("specie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("specie_id");

                    b.HasKey("Id")
                        .HasName("pk_breeds");

                    b.HasIndex("specie_id")
                        .HasDatabaseName("ix_breeds_specie_id");

                    b.ToTable("breeds", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.ComplexProperty<Dictionary<string, object>>("EmailAddress", "KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer.EmailAddress#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email_address");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("FullName", "KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("Patronymic")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("patronymic");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_volunteers");

                    b.ToTable("volunteers", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("creation_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("volunteer_id")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Age", "KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet.Age#Age", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("DateBirth")
                                .HasColumnType("date")
                                .HasColumnName("date_birth");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("CharacteristicsDetails", "KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet.CharacteristicsDetails#BiometricDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<float>("Height")
                                .HasColumnType("real")
                                .HasColumnName("height");

                            b1.Property<float>("Weight")
                                .HasColumnType("real")
                                .HasColumnName("weight");

                            b1.ComplexProperty<Dictionary<string, object>>("Gender", "KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet.CharacteristicsDetails#BiometricDetails.Gender#Gender", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("gender");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PetType", "KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet.PetType#PetType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("breed_id");

                            b1.Property<Guid>("SpecieId")
                                .HasColumnType("uuid")
                                .HasColumnName("specie_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("volunteer_id")
                        .HasDatabaseName("ix_pets_volunteer_id");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpecieManagement.Entities.Breed", b =>
                {
                    b.HasOne("KindPaws.Domain.Managements.SpecieManagement.AggregateRoot.Specie", null)
                        .WithMany("Breeds")
                        .HasForeignKey("specie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_breeds_species_specie_id");

                    b.OwnsOne("KindPaws.Domain.Managements.SpecieManagement.ValueObjects.Lists.BreedColorList", "ColorList", b1 =>
                        {
                            b1.Property<Guid>("BreedId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("BreedId");

                            b1.ToTable("breeds");

                            b1.ToJson("colors");

                            b1.WithOwner()
                                .HasForeignKey("BreedId")
                                .HasConstraintName("fk_breeds_breeds_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.SpecieManagement.ValueObjects.BreedColor", "BreedColors", b2 =>
                                {
                                    b2.Property<Guid>("BreedColorListBreedId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("BreedColorListBreedId", "Id")
                                        .HasName("pk_breeds");

                                    b2.ToTable("breeds");

                                    b2.WithOwner()
                                        .HasForeignKey("BreedColorListBreedId")
                                        .HasConstraintName("fk_breeds_breeds_breed_color_list_breed_id");
                                });

                            b1.Navigation("BreedColors");
                        });

                    b.Navigation("ColorList")
                        .IsRequired();
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer", b =>
                {
                    b.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.Lists.SocialNetworkList", "SocialNetworks", b1 =>
                        {
                            b1.Property<Guid>("VolunteerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("VolunteerId");

                            b1.ToTable("volunteers");

                            b1.ToJson("social_networks");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerId")
                                .HasConstraintName("fk_volunteers_volunteers_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.SocialNetwork", "SocialNetworks", b2 =>
                                {
                                    b2.Property<Guid>("SocialNetworkListVolunteerId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.HasKey("SocialNetworkListVolunteerId", "Id")
                                        .HasName("pk_volunteers");

                                    b2.ToTable("volunteers");

                                    b2.WithOwner()
                                        .HasForeignKey("SocialNetworkListVolunteerId")
                                        .HasConstraintName("fk_volunteers_volunteers_social_network_list_volunteer_id");
                                });

                            b1.Navigation("SocialNetworks");
                        });

                    b.Navigation("SocialNetworks")
                        .IsRequired();
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteerManagement.Entities.Pet", b =>
                {
                    b.HasOne("KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer", null)
                        .WithMany("Pets")
                        .HasForeignKey("volunteer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_pets_volunteers_volunteer_id");

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.HealthDetails", "HealthDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsNeutered")
                                .HasColumnType("boolean");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("health_details");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.Disease", "Diseases", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.HealthStatus", "HealthStatus", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HealthDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.Vaccine", "Vaccines", b2 =>
                                {
                                    b2.Property<Guid>("HealthDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HealthDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("HealthDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_health_details_pet_id");
                                });

                            b1.Navigation("Diseases");

                            b1.Navigation("HealthStatus")
                                .IsRequired();

                            b1.Navigation("Vaccines");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.Lists.PetPhotoList", "PhotosList", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("photos_details");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.PetPhoto", "Photos", b2 =>
                                {
                                    b2.Property<Guid>("PetPhotoListPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<bool>("IsMain")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("PathToStorage")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PetPhotoListPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("PetPhotoListPetId")
                                        .HasConstraintName("fk_pets_pets_pet_photo_list_pet_id");
                                });

                            b1.Navigation("Photos");
                        });

                    b.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.SupportDetails", "SupportDetails", b1 =>
                        {
                            b1.Property<Guid>("PetId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.ToJson("help_details");

                            b1.WithOwner()
                                .HasForeignKey("PetId")
                                .HasConstraintName("fk_pets_pets_id");

                            b1.OwnsMany("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.Requisite", "Requisites", b2 =>
                                {
                                    b2.Property<Guid>("SupportDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("SupportDetailsPetId", "Id")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("SupportDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_support_details_pet_id");
                                });

                            b1.OwnsOne("KindPaws.Domain.Managements.VolunteerManagement.ValueObjects.SupportStatus", "Status", b2 =>
                                {
                                    b2.Property<Guid>("SupportDetailsPetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("SupportDetailsPetId")
                                        .HasName("pk_pets");

                                    b2.ToTable("pets");

                                    b2.WithOwner()
                                        .HasForeignKey("SupportDetailsPetId")
                                        .HasConstraintName("fk_pets_pets_support_details_pet_id");
                                });

                            b1.Navigation("Requisites");

                            b1.Navigation("Status")
                                .IsRequired();
                        });

                    b.Navigation("HealthDetails")
                        .IsRequired();

                    b.Navigation("PhotosList")
                        .IsRequired();

                    b.Navigation("SupportDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.SpecieManagement.AggregateRoot.Specie", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("KindPaws.Domain.Managements.VolunteerManagement.AggregateRoot.Volunteer", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
