<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Accounts.Domain\KindPaws.Accounts.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\AccountRoles\Commands\" />
      <Folder Include="Features\AccountRoles\Queries\" />
      <Folder Include="Features\Accounts\Queries\" />
      <Folder Include="Features\RefreshSessions\Queries\" />
    </ItemGroup>

</Project>
