<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\KindPaws.Roles.Contracts\KindPaws.Roles.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Roles.Domain\KindPaws.Roles.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="KindPaws.Core" Version="1.0.8" />
      <PackageReference Include="KindPaws.SharedKernel" Version="1.1.3" />
    </ItemGroup>

</Project>
