<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0"/>
        <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Accounts\KindPaws.Accounts.Application\KindPaws.Accounts.Application.csproj" />
      <ProjectReference Include="..\Accounts\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\Accounts\KindPaws.Accounts.Domain\KindPaws.Accounts.Domain.csproj" />
      <ProjectReference Include="..\Accounts\KindPaws.Accounts.Infrastructure\KindPaws.Accounts.Infrastructure.csproj" />
      <ProjectReference Include="..\Accounts\KindPaws.Accounts.Presentation\KindPaws.Accounts.Presentation.csproj" />
      <ProjectReference Include="..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\Shared\KindPaws.Framework\KindPaws.Framework.csproj" />
      <ProjectReference Include="..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\Species\KindPaws.Species.Application\KindPaws.Species.Application.csproj" />
      <ProjectReference Include="..\Species\KindPaws.Species.Contracts\KindPaws.Species.Contracts.csproj" />
      <ProjectReference Include="..\Species\KindPaws.Species.Domain\KindPaws.Species.Domain.csproj" />
      <ProjectReference Include="..\Species\KindPaws.Species.Infrastructure\KindPaws.Species.Infrastructure.csproj" />
      <ProjectReference Include="..\Species\KindPaws.Species.Presentation\KindPaws.Species.Presentation.csproj" />
      <ProjectReference Include="..\Volunteers\KindPaws.Volunteers.Application\KindPaws.Volunteers.Application.csproj" />
      <ProjectReference Include="..\Volunteers\KindPaws.Volunteers.Contracts\KindPaws.Volunteers.Contracts.csproj" />
      <ProjectReference Include="..\Volunteers\KindPaws.Volunteers.Domain\KindPaws.Volunteers.Domain.csproj" />
      <ProjectReference Include="..\Volunteers\KindPaws.Volunteers.Infrastructure\KindPaws.Volunteers.Infrastructure.csproj" />
      <ProjectReference Include="..\Volunteers\KindPaws.Volunteers.Presentation\KindPaws.Volunteers.Presentation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DI\Injections\Authentication\" />
    </ItemGroup>    

</Project>
