<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>KindPaws.Accounts.Presentation</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="KindPaws.Framework" Version="1.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\KindPaws.Accounts.Application\KindPaws.Accounts.Application.csproj" />
      <ProjectReference Include="..\KindPaws.Accounts.Contracts\KindPaws.Accounts.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Accounts.Domain\KindPaws.Accounts.Domain.csproj" />
      <ProjectReference Include="..\KindPaws.Accounts.Infrastructure\KindPaws.Accounts.Infrastructure.csproj" />
    </ItemGroup>   

</Project>
