<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\KindPaws.Auth.Contracts\KindPaws.Auth.Contracts.csproj" />
      <ProjectReference Include="..\KindPaws.Auth.Domain\KindPaws.Auth.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Accounts\Commands\" />
      <Folder Include="Features\Accounts\Queries\" />
      <Folder Include="Features\Permissions\Commands\" />
      <Folder Include="Features\Permissions\EventHandlers\" />
      <Folder Include="Features\Permissions\Queries\" />
      <Folder Include="Features\Roles\Commands\" />
      <Folder Include="Features\Roles\Queries\" />
    </ItemGroup>

</Project>
