<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>        
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>KindPaws.SharedKernel</PackageId>
        <Version>1.0.7</Version>
        <Authors>initaIe</Authors>
        <Description>Shared Kernel for KindPaws project</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/initaIe/KindPaws</RepositoryUrl>
    </PropertyGroup>

</Project>
