services:
  
  seq:
    image: datalust/seq:latest
    container_name: seq_container
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:5341"
    networks:
      - app-network
    volumes:
      - seq:/data
  
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: kind_paws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG-DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: jayzwalkinz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: jayzwalkinz
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  seq: