<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.Framework\KindPaws.Framework.csproj" />
      <ProjectReference Include="..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
      <ProjectReference Include="..\KindPaws.Species.Application\KindPaws.Species.Application.csproj" />
      <ProjectReference Include="..\KindPaws.Species.Domain\KindPaws.Species.Domain.csproj" />
    </ItemGroup>    

</Project>
