// <auto-generated />
using System;
using System.Collections.Generic;
using KindPaws.Species.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KindPaws.Species.Infrastructure.Migrations
{
    [DbContext(typeof(SpeciesWriteDbContext))]
    [Migration("20241117132107_Species_20241117_181940")]
    partial class Species_20241117_181940
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("species")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindPaws.Species.Domain.AggregateRoot.Specie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_soft_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SoftDeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_delete_datetime");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "KindPaws.Species.Domain.AggregateRoot.Specie.Description#MediumDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("description");
                        });

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_species_name");

                    b.ToTable("species", "species");
                });

            modelBuilder.Entity("KindPaws.Species.Domain.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsSoftDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_soft_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("citext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SoftDeletedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("soft_delete_datetime");

                    b.Property<Guid>("specie_id")
                        .HasColumnType("uuid")
                        .HasColumnName("specie_id");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "KindPaws.Species.Domain.Entities.Breed.Description#MediumDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("description");
                        });

                    b.HasKey("Id")
                        .HasName("pk_breeds");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_breeds_name");

                    b.HasIndex("specie_id")
                        .HasDatabaseName("ix_breeds_specie_id");

                    b.ToTable("breeds", "species");
                });

            modelBuilder.Entity("KindPaws.Species.Domain.Entities.Breed", b =>
                {
                    b.HasOne("KindPaws.Species.Domain.AggregateRoot.Specie", null)
                        .WithMany("Breeds")
                        .HasForeignKey("specie_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_breeds_species_specie_id");
                });

            modelBuilder.Entity("KindPaws.Species.Domain.AggregateRoot.Specie", b =>
                {
                    b.Navigation("Breeds");
                });
#pragma warning restore 612, 618
        }
    }
}
