name: Publish Packages

on:
  push:
    paths:
      - 'KindPaws/KindPaws.Shared/KindPaws.SharedKernel/**'
      - 'KindPaws/KindPaws.Shared/KindPaws.Core/**'
      - 'KindPaws/KindPaws.Shared/KindPaws.Framework/**'
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish KindPaws.Core to GitHub Packages
        run: |
          dotnet pack KindPaws/KindPaws.Shared/KindPaws.Core/KindPaws.Core.csproj --configuration Release --output ./nupkgs
          dotnet nuget push ./nupkgs/*.nupkg --source "GitHub" --api-key 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

      - name: Publish KindPaws.SharedKernel to GitHub Packages
        run: |
          dotnet pack KindPaws/KindPaws.Shared/KindPaws.SharedKernel/KindPaws.SharedKernel.csproj --configuration Release --output ./nupkgs
          dotnet nuget push ./nupkgs/*.nupkg --source "GitHub" --api-key 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

      - name: Publish KindPaws.Framework to GitHub Packages
        run: |
          dotnet pack KindPaws/KindPaws.Shared/KindPaws.Framework/KindPaws.Framework.csproj --configuration Release --output ./nupkgs
          dotnet nuget push ./nupkgs/*.nupkg --source "GitHub" --api-key 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