env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
  NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
  DOTNET_VERSION: 8.0.x
  SOLUTION_PATH: ./KindPaws.Shared/KindPaws.Core
  PROJECT_PATH: ${{ env.SOLUTION_PATH }}/src/KindPaws.Core
  PATH_TO_SLN: ${{ env.SOLUTION_PATH }}/KindPaws.Core.sln
  PATH_TO_CSPROJ: ${{ env.PROJECT_PATH }}/KindPaws.Core.csproj
  PACKAGE_EXSTENSION_NAME: nupkg
  PACKAGE_NAME: KindPaws.Core
  

name: KinPaws.Core  

on:
  push:
    branches:
      - Dev
    paths:
      - 'KindPaws.Shared/KindPaws.Core/**/*'

jobs:
  build:
    name: Build And Publish Package ${{ env.PACKAGE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Authenticate with GitHub Packages
        run: >
          dotnet nuget add source
          ${{ env.NUGET_SOURCE }} --name github
          --username ${{ env.NUGET_USERNAME }} --password ${{ env.NUGET_PASSWORD }}

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Restore dependencies
        run: dotnet restore ${{ env.PATH_TO_SLN }}

      - name: Get version from .csproj
        id: version
        run: |
          VERSION=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" ${{ env.PATH_TO_CSPROJ }})
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build ${{ env.PATH_TO_SLN }} --configuration Release --no-restore

      - name: Pack NuGet package
        run: >
          dotnet pack ${{ env.PATH_TO_SLN }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:PackageId=${{ env.PACKAGE_NAME }}

      - name: Publish
        run: >
          dotnet nuget push ${{ env.PROJECT_PATH }}/bin/Release/${{ env.PACKAGE_NAME }}.${{ env.PACKAGE_VERSION }}.${{ env.PACKAGE_EXSTENSION_NAME }}
          -s ${{ env.NUGET_SOURCE }}
          -k ${{ env.NUGET_PASSWORD }}