name: Publish Core NuGet

on:
  push:
    branches:
      - Dev
    paths:
      - 'KindPaws.Shared/KindPaws.Core/**/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Убедитесь, что используете правильную версию SDK

      - name: Authenticate with GitHub Packages
  	run: |
    	  dotnet nuget add source https://nuget.pkg.github.com/initaIe/index.json --name github --username initaIe --password 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

      - name: Build
        run: |
          dotnet pack KindPaws.Shared/KindPaws.Core/src/KindPaws.Core --configuration Release --output ./artifacts

      - name: Publish
        env:
          NUGET_AUTH_TOKEN: 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
        run: |
          dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/initaIe/index.json"