name: KinPaws.Framework

env:
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

on:
  push:
    branches:
      - Dev
    paths:
      - 'KindPaws.Shared/KindPaws.Framework/**/*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Authenticate with GitHub Packages
        run: >
          dotnet nuget add source
          https://nuget.pkg.github.com/$NUGET_USERNAME/index.json --name github
          --username $NUGET_USERNAME --password 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 --store-password-in-clear-text

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Restore dependencies
        run: dotnet restore ./KindPaws.Shared/KindPaws.Framework/KindPaws.Framework.sln

      - name: Get version from .csproj
        id: version
        run: |
          VERSION=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" ./KindPaws.Shared/KindPaws.Framework/src/KindPaws.Framework/KindPaws.Framework.csproj)
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build
        run: dotnet build ./KindPaws.Shared/KindPaws.Framework/KindPaws.Framework.sln --configuration Release --no-restore

      - name: Pack NuGet package
        run: >
          dotnet pack ./KindPaws.Shared/KindPaws.Framework/KindPaws.Framework.sln --no-restore --no-build --configuration Release -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:PackageId=KindPaws.Framework

      - name: Publish
        run: >
          dotnet nuget push ./KindPaws.Shared/KindPaws.Framework/src/KindPaws.Framework/bin/Release/KindPaws.Framework.${{ env.PACKAGE_VERSION }}.nupkg
          -s https://nuget.pkg.github.com/$NUGET_USERNAME/index.json
          -k $NUGET_PASSWORD