name: Publish Core NuGet

on:
  push:
    branches:
      - Dev
    paths:
      - 'KindPaws/KindPaws.Shared/KindPaws.Core/src/KindPaws.Core/KindPaws.Core.csproj'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Убедитесь, что используете правильную версию SDK

      - name: Restore dependencies
        run: |
          dotnet restore KindPaws/KindPaws.Shared/KindPaws.Core/src/KindPaws.Core/KindPaws.Core.csproj

      - name: Build project
        run: |
          dotnet build KindPaws/KindPaws.Shared/KindPaws.Core/src/KindPaws.Core/KindPaws.Core.csproj --configuration Release

      - name: Pack the project
        run: |
          dotnet pack KindPaws/KindPaws.Shared/KindPaws.Core/src/KindPaws.Core/KindPaws.Core.csproj --configuration Release --output ./artifacts

      - name: Push NuGet package to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: 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
        run: |
          dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/initaIe/index.json"