<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\KindPaws.Core\KindPaws.Core.csproj" />
      <ProjectReference Include="..\..\..\Shared\KindPaws.SharedKernel\KindPaws.SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Messaging\" />
      <Folder Include="Requests\" />
      <Folder Include="Responses\" />
    </ItemGroup>

</Project>
